name: SlotMachine
main: fr.klemms.slotmachine.SlotPlugin
version: 6.5.7
softdepend: [Vault, Multiverse-Core, MultiWorld, GamePoints, TokenManager, Citizens, ReWorld, UltraRegions, VotingPlugin, My_Worlds]
load: POSTWORLD
author: Klemms
api-version: 1.16
commands:
    slotmachineversion:
        description: Tells you Slot Machine's version
        usage: /slotmachineversion
    slotmachine:
        description: Gives the Slot Machine maker tool
        usage: /slotmachine
        permission: slotmachine.slotmachine
        permission-message: You do not have permission
    openmachine:
        description: Opens a Slot Machine for a player
        usage: /openmachine <Player Name> <Machine UUID> [true/false | true to override the machine's permission]
        permission: slotmachine.openmachine
        permission-message: You do not have permission
    tpmachine:
        description: Teleports a machine to you, at the same exact position
        usage: /tpmachine <Entity UUID>
        permission: slotmachine.tpmachine
        permission-message: You do not have permission
    givetokens:
        description: Gives the player the amount of tokens, omitting or mistyping the Token ID will bring up a UI that lets you pick the Token you want
        usage: /givetokens <Player Name> <Amount of Tokens> [Token ID]
        permission: slotmachine.givetokens
        permission-message: You do not have permission
    slotmachinetoken:
        description: Helps you manage your tokens
        usage: /slotmachinetoken list OR /slotmachinetoken add <unique name (lower case, one word)>
        permission: slotmachine.tokenmanagement
        permission-message: You do not have permission
    smsavetodisk:
        description: Forces Slot Machine to write any change you've made to disk
        usage: /smsavetodisk
        permission: slotmachine.slotmachine
        permission-message: You do not have permission
    smcooldown:
        description: Resets cooldowns for players
        usage: /smcooldown <player/@a(all players online)/@everyone(all players)> <slot machine uuid/all> reset
        permission: slotmachine.smcooldown
        permission-message: You do not have permission